/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    places: Place;
    collections: Collection;
    regions: Region;
    'blog-posts': BlogPost;
    'candidate-places': CandidatePlace;
    'discovery-runs': DiscoveryRun;
    'booking-inquiries': BookingInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'candidate-places': CandidatePlacesSelect<false> | CandidatePlacesSelect<true>;
    'discovery-runs': DiscoveryRunsSelect<false> | DiscoveryRunsSelect<true>;
    'booking-inquiries': BookingInquiriesSelect<false> | BookingInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    about: About;
    'journal-page': JournalPage;
    'sammlungen-page': SammlungenPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
    'sammlungen-page': SammlungenPageSelect<false> | SammlungenPageSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: string;
  title: string;
  slug: string;
  region: string | Region;
  /**
   * Längengrad, Breitengrad — Pflicht für Karten-Anzeige
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  shortStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whyDisconnect?:
    | {
        reason: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 3–5 Merkmale auswählen
   */
  attributes?:
    | ('funkloch' | 'see' | 'berge' | 'wald' | 'design' | 'adults-only' | 'eco' | 'retreat' | 'chalet' | 'boutique')[]
    | null;
  /**
   * Zielgruppe auswählen
   */
  audience?: ('reset' | 'paare' | 'solo' | 'offsite' | 'hund')[] | null;
  /**
   * 1 = Ruhig, 2 = Sehr ruhig, 3 = Absolut still
   */
  quietnessLevel?: ('1' | '2' | '3') | null;
  /**
   * Konkrete Merkmale, die den Ort ruhig machen
   */
  quietnessTraits?:
    | (
        | 'no-road-noise'
        | 'small-house'
        | 'no-cell-signal'
        | 'adults-only'
        | 'no-wifi'
        | 'nature-only'
        | 'secluded'
        | 'no-tv'
        | 'digital-detox'
        | 'silent-zones'
      )[]
    | null;
  priceRange?: ('budget' | 'mid' | 'premium' | 'luxury') | null;
  heroImage: string | Media;
  gallery?: (string | Media)[] | null;
  /**
   * Link zur offiziellen Website
   */
  outboundUrl?: string | null;
  /**
   * Wird für Buchungsanfragen verwendet — nie öffentlich sichtbar
   */
  contactEmail?: string | null;
  /**
   * Optional — Standard: "Warum hier abschalten"
   */
  whyDisconnectHeading?: string | null;
  /**
   * Optional — Standard: "Website besuchen"
   */
  ctaLabel?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: string;
  title: string;
  slug: string;
  intro?: string | null;
  heroImage?: (string | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: string;
  title: string;
  slug: string;
  intro?: string | null;
  /**
   * 4–6 Sätze für Listings und SEO
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (string | null) | Media;
  /**
   * Kuratierte Auswahl von Orten (Reihenfolge beachten)
   */
  places?: (string | Place)[] | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedCollections?: (string | Collection)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  category: 'region' | 'sammlung' | 'editorial' | 'intent-seo';
  heroImage: string | Media;
  /**
   * 4–6 Sätze für Listing und SEO
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 2–8 Orte verknüpfen
   */
  relatedPlaces?: (string | Place)[] | null;
  relatedCollections?: (string | Collection)[] | null;
  relatedRegions?: (string | Region)[] | null;
  /**
   * Freie Tags für Filterung und SEO
   */
  tags?: string[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-places".
 */
export interface CandidatePlace {
  id: string;
  name: string;
  websiteUrl: string;
  mapsUrl?: string | null;
  contactEmail?: string | null;
  snippet?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  regionGuess?: string | null;
  source?: string | null;
  qualityScore?: number | null;
  reasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  riskFlags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confidence?: number | null;
  ratingValue?: number | null;
  reviewCount?: number | null;
  status?: ('new' | 'maybe' | 'accepted' | 'rejected') | null;
  rejectionReason?: string | null;
  /**
   * Auto-generiert bei Acceptance
   */
  generatedEmail?: string | null;
  calibrationLabel?: ('perfect' | 'good' | 'borderline' | 'wrong') | null;
  needsManualCheck?: boolean | null;
  dedupeKey: string;
  discoveryRunId?: (string | null) | DiscoveryRun;
  acceptedPlaceId?: (string | null) | Place;
  images?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Original SERP + enrichment data
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-runs".
 */
export interface DiscoveryRun {
  id: string;
  preset?: string | null;
  query?: string | null;
  region?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  status?: ('running' | 'completed' | 'failed') | null;
  stats?: {
    candidatesFound?: number | null;
    newCandidates?: number | null;
    duplicatesSkipped?: number | null;
    errorCount?: number | null;
  };
  progress?: {
    phase?: ('searching' | 'processing' | 'finalizing') | null;
    processed?: number | null;
    total?: number | null;
  };
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-inquiries".
 */
export interface BookingInquiry {
  id: string;
  name: string;
  email: string;
  message: string;
  checkIn?: string | null;
  checkOut?: string | null;
  place: string | Place;
  /**
   * Denormalisierter Ortstitel zum Zeitpunkt der Anfrage
   */
  placeTitle?: string | null;
  /**
   * Ob die E-Mail-Benachrichtigung erfolgreich versendet wurde
   */
  emailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'places';
        value: string | Place;
      } | null)
    | ({
        relationTo: 'collections';
        value: string | Collection;
      } | null)
    | ({
        relationTo: 'regions';
        value: string | Region;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'candidate-places';
        value: string | CandidatePlace;
      } | null)
    | ({
        relationTo: 'discovery-runs';
        value: string | DiscoveryRun;
      } | null)
    | ({
        relationTo: 'booking-inquiries';
        value: string | BookingInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  region?: T;
  coordinates?: T;
  shortStory?: T;
  whyDisconnect?:
    | T
    | {
        reason?: T;
        id?: T;
      };
  attributes?: T;
  audience?: T;
  quietnessLevel?: T;
  quietnessTraits?: T;
  priceRange?: T;
  heroImage?: T;
  gallery?: T;
  outboundUrl?: T;
  contactEmail?: T;
  whyDisconnectHeading?: T;
  ctaLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  places?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedCollections?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  heroImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedPlaces?: T;
  relatedCollections?: T;
  relatedRegions?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-places_select".
 */
export interface CandidatePlacesSelect<T extends boolean = true> {
  name?: T;
  websiteUrl?: T;
  mapsUrl?: T;
  contactEmail?: T;
  snippet?: T;
  coordinates?: T;
  regionGuess?: T;
  source?: T;
  qualityScore?: T;
  reasons?: T;
  riskFlags?: T;
  confidence?: T;
  ratingValue?: T;
  reviewCount?: T;
  status?: T;
  rejectionReason?: T;
  generatedEmail?: T;
  calibrationLabel?: T;
  needsManualCheck?: T;
  dedupeKey?: T;
  discoveryRunId?: T;
  acceptedPlaceId?: T;
  images?: T;
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-runs_select".
 */
export interface DiscoveryRunsSelect<T extends boolean = true> {
  preset?: T;
  query?: T;
  region?: T;
  startedAt?: T;
  completedAt?: T;
  status?: T;
  stats?:
    | T
    | {
        candidatesFound?: T;
        newCandidates?: T;
        duplicatesSkipped?: T;
        errorCount?: T;
      };
  progress?:
    | T
    | {
        phase?: T;
        processed?: T;
        total?: T;
      };
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-inquiries_select".
 */
export interface BookingInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  checkIn?: T;
  checkOut?: T;
  place?: T;
  placeTitle?: T;
  emailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  heroImage?: (string | null) | Media;
  heroLabel?: string | null;
  heroHeadline?: string | null;
  heroSubheadline?: string | null;
  heroCTALabel?: string | null;
  placesLabel?: string | null;
  placesHeading?: string | null;
  placesCTALabel?: string | null;
  collectionsLabel?: string | null;
  collectionsHeading?: string | null;
  journalLabel?: string | null;
  journalHeading?: string | null;
  journalCTALabel?: string | null;
  trustOrteLabel?: string | null;
  trustRegionenLabel?: string | null;
  trustSammlungenLabel?: string | null;
  regionEmptyMessage?: string | null;
  mapHeading?: string | null;
  mapSubheading?: string | null;
  mapCTALabel?: string | null;
  newsletterHeading?: string | null;
  introText: string;
  atmosphereImage?: (string | null) | Media;
  atmosphereText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: string;
  label?: string | null;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sammlungen-page".
 */
export interface SammlungenPage {
  id: string;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroImage?: T;
  heroLabel?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroCTALabel?: T;
  placesLabel?: T;
  placesHeading?: T;
  placesCTALabel?: T;
  collectionsLabel?: T;
  collectionsHeading?: T;
  journalLabel?: T;
  journalHeading?: T;
  journalCTALabel?: T;
  trustOrteLabel?: T;
  trustRegionenLabel?: T;
  trustSammlungenLabel?: T;
  regionEmptyMessage?: T;
  mapHeading?: T;
  mapSubheading?: T;
  mapCTALabel?: T;
  newsletterHeading?: T;
  introText?: T;
  atmosphereImage?: T;
  atmosphereText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sammlungen-page_select".
 */
export interface SammlungenPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}